
(25, 'Inappropriate ioctl for device')
[nltk_data] Downloading package punkt to
[nltk_data]     /cluster/home/julievt/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "/cluster/home/julievt/master-project/./scripts/train/tre/tlink/main.py", line 72, in <module>
    ner = TRExtract(
          ^^^^^^^^^^
  File "/cluster/home/julievt/master-project/src/textmining/tre/setup.py", line 127, in __init__
    dataset, tags = self.__tlink(dataset_tre, dataset_ner, dataset_tee)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/julievt/master-project/src/textmining/tre/setup.py", line 232, in __tlink
    raise ValueError("FINISHED")
ValueError: FINISHED
