
(25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/cluster/home/julievt/master-project/./scripts/train/tlink.py", line 37, in <module>
    ner = TRExtract(
          ^^^^^^^^^^
  File "/cluster/home/julievt/master-project/src/textmining/tre/setup.py", line 45, in __init__
    "early_stopping_delta": self.__config.getint("train.parameters", "early_stopping_delta"),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/eb/software/Python/3.12.3-GCCcore-13.3.0/lib/python3.12/configparser.py", line 796, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/eb/software/Python/3.12.3-GCCcore-13.3.0/lib/python3.12/configparser.py", line 786, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/apps/eb/software/Python/3.12.3-GCCcore-13.3.0/lib/python3.12/configparser.py", line 781, in _get
    return conv(self.get(section, option, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0.01'
